server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: trading-bot
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading-bot
          container: solana-trading-bot
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: output
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
      - output:
          source: output
      - match:
          selector: '{container="solana-trading-bot"}'
          stages:
            # Парсим JSON логи из поля log
            - json:
                expressions:
                  log_content: log
            - json:
                expressions:
                  level: level
                  time: time
                  msg: msg
                  code: code
                  dex: dex
                  base: base
                  quote: quote
                  pool: pool
                  mint: mint
                  reason: reason
                  signature: signature
                  error: error
                  filter: filterName
                  poolId: poolId
                  tokenName: tokenName
                  tokenSymbol: tokenSymbol
                source: log_content
            - labels:
                level:
                code:
                dex:
                filter:
                pool:
                base:
                quote:
                msg:
                tokenName:
                tokenSymbol:
            - timestamp:
                source: time
                format: RFC3339Nano